name: Terraform CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: | 
          terraform init \
            -backend-config="bucket=${{ vars.TF_REMOTE_STATE_BUCKET }}"
      
      - name: terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan -var="bucket_name=${{ vars.TF_VAR_BUCKET_NAME }}"

      - name: Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: terrform destroy
        run: terraform destroy -auto-approve

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init -backend-config="bucket=${{ vars.TF_REMOTE_STATE_BUCKET }}"

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  

